### ISSUE TITLE
CORS Error trying to update Whitelist

### ISSUE THREAD

**Issue by guice** [hassio-addons/addon-pi-hole#126]
# Problem/Motivation

I'm getting a CORS error trying to update the Whitelist, even though the Addon Admin screen still works.

## Expected behavior

The hostname get added

## Actual behavior

CORS error:
<img width="1324" alt="Screen Shot 2020-03-02 at 8 21 05 AM" src="https://user-images.githubusercontent.com/205378/75690220-b534b400-5c5f-11ea-9206-6ed853b85c6a.png">

My configuration:

```yaml
update_lists_on_start: false
ssl: true
certfile: ven[redacted]
keyfile: ven[redacted]
interface: ''
ipv6: true
ipv4_address: ''
ipv6_address: ''
hosts:
  - name: [redacted].local
    ip: 192.168.0.88
  - name: ven[redacted]
    ip: 192.168.0.88
  - name: [redacted].local
    ip: 192.168.0.69
virtual_host: ven[redacted]
```

Might be related to: https://github.com/hassio-addons/addon-pi-hole/pull/90
