### ISSUE TITLE
Pi-Hole Add-on Fails to Load, Inaccessible from Web UI or curl

### ISSUE THREAD

**Issue by alderete** [hassio-addons/addon-pi-hole#127]
# Problem/Motivation

The 4.1.1 version of the Pi-Hole add-on is now completely broken with HA .106.5 (latest release as of this writing).

- The web UI does not load, instead returning a "502: Bad Gateway" error.
- The add-on Logs repeats the following error every few seconds: "nginx: [emerg] invalid number of arguments in "resolver" directive in /etc/nginx/includes/resolver.conf:1"

## Expected behavior

The Pi-Hole add-on to load without errors, the web UI to be accessible, and the API accessible via the command line using the following curl command: curl -X GET 'http://192.168.1.9:4865/admin/api.php?status'

## Actual behavior

- The web UI does not load, instead returning a "502: Bad Gateway" error.
- The add-on Logs repeats the following error every few seconds: "nginx: [emerg] invalid number of arguments in "resolver" directive in /etc/nginx/includes/resolver.conf:1"

## Steps to reproduce

Update to Pi-Hole add-on 4.1.1, and HA .106.5. Start a formerly working add-on.

## Proposed changes

Revert to 4.0...?

**Comment by alderete** [comment]
To add a bit of color, HA is running in a VM (VirtualBox, latest release). 

Home Assistant appears to be running fine otherwise. 

The add-on was failing to be accessible via the command line or via the sensors from the integration with add-on versions 4.1 and 4.1.1 and HA versions prior to .106.5. It's only with the update to .106.5 that the add-on is completely dead.

**Comment by alderete** [comment]
Here's my add-on config:

```
update_lists_on_start: false
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
interface: ''
ipv6: false
ipv4_address: ''
ipv6_address: ''
hosts:
  - name: caboodle.local
    ip: 192.168.1.5
  - name: homeassistant.local
    ip: 192.168.1.9
virtual_host: ''
```

And here's my integration config:

```
---
# https://www.home-assistant.io/integrations/pi_hole/
pi_hole:
  - host: !secret host_pihole_synology
    name: 'Primary Pi-Hole'
    api_key: !secret pihole_api_key_synology
  - host: !secret host_pihole_hassio # (value: 192.168.1.9:4865)
    name: 'Secondary Pi-Hole'
    api_key: !secret pihole_api_key_hassio # (value: '', that is, an empty string)
```
