### ISSUE TITLE
README.md typo

### ISSUE THREAD

**Issue by mcfrojd** [hassio-addons/addon-pi-hole#16]
Example configuration:

```
panel_iframe:
  terminal:
    title: Pi-hole
    icon: mdi:block-helper
    url: http://addres.to.your.hass.io/admin/index.php
```
Maybe should be:

```
panel_iframe:
  pihole:
    title: Pi-hole
    icon: mdi:block-helper
    url: http://addres.to.your.hass.io/admin/index.php
```
