### ISSUE TITLE
Update component example for v2

### ISSUE THREAD

**Issue by frenck** [hassio-addons/addon-pi-hole#38]
# Problem/Motivation

The add-on changed its default port and admin location since v2 of the add-on.

The documentation was not updated to reflect this.

**Comment by tjorim** [comment]
Both panel_iframe and sensor components needs updating.
The example you posted on the forums however, seems incorrect:
```
sensor:
  - platform: pi_hole
    host: localhost:4865
    location: ""
```
Isn't the admin panel still on `/admin` (and the matching API endpoint on `/admin/api.php` as per the [docs](https://github.com/pi-hole/AdminLTE#api)?
