### ISSUE TITLE
pihole addon no sensors

### ISSUE THREAD

**Issue by h4nc** [hassio-addons/addon-pi-hole#62]
# Problem/Motivation

Sensors don't show up in home assistant running the hassio addon.

This is my config in sensors.yaml

```
 - platform: pi_hole
  host: localhost:4865
  ssl: true 
  monitored_conditions:
    - ads_blocked_today
    - dns_queries_today
    - domains_being_blocked
    - unique_clients
    - clients_ever_seen
```

This is the error I get. Is it a known bug?

`Can not load data from *hole: localhost:4865`
