### ISSUE TITLE
There is no option to specify admin password on the pi-hole sensor

### ISSUE THREAD

**Issue by danielo515** [hassio-addons/addon-pi-hole#87]
# Problem/Motivation

pi-hole addon is working fine, but I can not setup the sensors on a different home-assistant machine.
Sensors are displayed as not available

## Expected behavior

I want to see my pi-hole sensor information on another machine (not localhost) running home assistant.

## Steps to reproduce

Setup an admin password and try to add sensors on a different home assistant machine.
I have defined the admin port like this:

```
sensor:
  - platform: pi_hole
    host: hassio.local:4865
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - dns_queries_today
      - domains_being_blocked
      - queries_cached
      - queries_forwarded
      - unique_clients
      - unique_domains
```

But there is no option to setup admin_password, so I guess that is the reason why it is failing.
